import type { Listing } from "@/types";

/** 20 realistic seed listings across Dhaka for demo purposes */
export const SEED_LISTINGS: Omit<Listing, "profiles">[] = [
  {
    id: "1",
    landlord_id: "landlord-1",
    title_en: "Spacious 2-Bed Flat Near IUT Gate",
    title_bn: "আইইউটি গেটের পাশে প্রশস্ত ২ রুমের ফ্ল্যাট",
    description_en: "A well-maintained 2-bedroom flat ideal for IUT students. Located just 5 minutes walk from the university gate. The flat features a separate kitchen, tiled bathrooms, and good natural lighting.",
    description_bn: "আইইউটি শিক্ষার্থীদের জন্য আদর্শ ২ রুমের সুসজ্জিত ফ্ল্যাট। বিশ্ববিদ্যালয় গেট থেকে মাত্র ৫ মিনিটের হাঁটার দূরত্বে।",
    area: "Mirpur-11",
    address: "Road 12, Block C, Mirpur-11, Dhaka",
    lat: 23.8267,
    lng: 90.3667,
    rent_bdt: 9500,
    rooms: 2,
    bathrooms: 1,
    floor: 3,
    furnishing: "semi",
    type: "student",
    for_gender: "male",
    utilities_included: false,
    photos: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    ],
    is_available: true,
    trust_score: 82,
    trust_score_breakdown: {
      price: { score: 25, note: "Rent is within expected range." },
      photos: { score: 20, note: "Excellent photo evidence." },
      description: { score: 15, note: "Clear description provided." },
      duplicate: { score: 10, note: "Passed NLP duplicate check." },
      photo_hash: { score: 15, note: "Original photos verified by pHash." }
    },
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    landlord_id: "landlord-2",
    title_en: "Cozy Studio for Female Students – Dhanmondi",
    title_bn: "ধানমন্ডিতে ছাত্রীদের জন্য কোজি স্টুডিও",
    description_en: "Safe and quiet studio apartment perfect for female students or working women. Located in a secure building with CCTV, close to markets and transport links.",
    description_bn: "নিরাপদ ও শান্ত পরিবেশে ছাত্রী বা কর্মজীবী নারীদের জন্য স্টুডিও অ্যাপার্টমেন্ট। সিসিটিভি সহ নিরাপদ বিল্ডিংয়ে অবস্থিত।",
    area: "Dhanmondi",
    address: "House 7/A, Road 4, Dhanmondi, Dhaka",
    lat: 23.7461,
    lng: 90.3742,
    rent_bdt: 12000,
    rooms: 1,
    bathrooms: 1,
    floor: 2,
    furnishing: "fully",
    type: "student",
    for_gender: "female",
    utilities_included: true,
    photos: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800",
    ],
    is_available: true,
    trust_score: 91,
    trust_score_breakdown: {
      price: { score: 25, note: "Rent is within expected range." },
      photos: { score: 20, note: "Excellent photo evidence." },
      description: { score: 15, note: "Clear description provided." },
      duplicate: { score: 10, note: "Passed NLP duplicate check." },
      photo_hash: { score: 15, note: "Original photos verified by pHash." }
    },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    landlord_id: "landlord-3",
    title_en: "Family Flat – 3 Beds, Uttara Sector 7",
    title_bn: "উত্তরা সেক্টর ৭-এ পারিবারিক ফ্ল্যাট – ৩ রুম",
    description_en: "A spacious 3-bedroom family apartment in the peaceful Uttara Sector 7. Features a large living area, modern kitchen, two attached bathrooms, and a balcony with open views.",
    description_bn: "উত্তরার শান্তিপ্রিয় সেক্টর ৭-এ প্রশস্ত ৩ রুমের পারিবারিক অ্যাপার্টমেন্ট। বড় লিভিং রুম, আধুনিক রান্নাঘর এবং দুটি সংযুক্ত বাথরুম সহ।",
    area: "Uttara",
    address: "Road 3, Sector 7, Uttara, Dhaka",
    lat: 23.8759,
    lng: 90.3795,
    rent_bdt: 22000,
    rooms: 3,
    bathrooms: 2,
    floor: 4,
    furnishing: "semi",
    type: "family",
    for_gender: "any",
    utilities_included: false,
    photos: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800",
      "https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800",
    ],
    is_available: true,
    trust_score: 78,
    trust_score_breakdown: {
      price: { score: 25, note: "Rent is within expected range." },
      photos: { score: 20, note: "Excellent photo evidence." },
      description: { score: 15, note: "Clear description provided." },
      duplicate: { score: 10, note: "Passed NLP duplicate check." },
      photo_hash: { score: 15, note: "Original photos verified by pHash." }
    },
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    landlord_id: "landlord-4",
    title_en: "Budget 1-Bed Near DUET, Gazipur",
    title_bn: "ডুয়েটের কাছে সাশ্রয়ী ১ রুমের ফ্ল্যাট",
    description_en: "Affordable single room flat for DUET students. Only 10 minutes from campus. Clean bathroom, kitchen access, and reliable electricity with backup generator.",
    description_bn: "ডুয়েট শিক্ষার্থীদের জন্য সাশ্রয়ী মূল্যের একক রুমের ফ্ল্যাট। ক্যাম্পাস থেকে মাত্র ১০ মিনিটের দূরত্বে।",
    area: "Mirpur-2",
    address: "Gazipur Sadar, Near DUET Gate",
    lat: 23.9827,
    lng: 90.4218,
    rent_bdt: 6500,
    rooms: 1,
    bathrooms: 1,
    floor: 1,
    furnishing: "unfurnished",
    type: "student",
    for_gender: "male",
    utilities_included: false,
    photos: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    ],
    is_available: true,
    trust_score: 62,
    trust_score_breakdown: {
      price: { score: 25, note: "Rent is within expected range." },
      photos: { score: 20, note: "Excellent photo evidence." },
      description: { score: 15, note: "Clear description provided." },
      duplicate: { score: 10, note: "Passed NLP duplicate check." },
      photo_hash: { score: 15, note: "Original photos verified by pHash." }
    },
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    landlord_id: "landlord-5",
    title_en: "Modern 2-Bed in Bashundhara R/A",
    title_bn: "বসুন্ধরা আবাসিক এলাকায় আধুনিক ২ রুমের ফ্ল্যাট",
    description_en: "Contemporary 2-bedroom apartment in Bashundhara Residential Area. Close to North South University and East West University. Fully tiled, gas line, and 24/7 security.",
    description_bn: "বসুন্ধরা আবাসিক এলাকায় আধুনিক ২ রুমের অ্যাপার্টমেন্ট। নর্থ সাউথ ও ইস্ট ওয়েস্ট বিশ্ববিদ্যালয়ের কাছে।",
    area: "Bashundhara R/A",
    address: "Block C, Road 5, Bashundhara R/A, Dhaka",
    lat: 23.8157,
    lng: 90.4292,
    rent_bdt: 16000,
    rooms: 2,
    bathrooms: 2,
    floor: 5,
    furnishing: "semi",
    type: "professional",
    for_gender: "any",
    utilities_included: false,
    photos: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800",
    ],
    is_available: true,
    trust_score: 88,
    trust_score_breakdown: {
      price: { score: 25, note: "Rent is within expected range." },
      photos: { score: 20, note: "Excellent photo evidence." },
      description: { score: 15, note: "Clear description provided." },
      duplicate: { score: 10, note: "Passed NLP duplicate check." },
      photo_hash: { score: 15, note: "Original photos verified by pHash." }
    },
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    landlord_id: "landlord-6",
    title_en: "Shared Room for Students – Mohammadpur",
    title_bn: "মোহাম্মদপুরে শিক্ষার্থীদের জন্য শেয়ার্ড রুম",
    description_en: "Budget-friendly shared room for 2 students in Mohammadpur. Each person gets personal storage space. Shared kitchen and bathroom kept clean. Perfect for IUT/BUET students.",
    description_bn: "মোহাম্মদপুরে ২ শিক্ষার্থীর জন্য সাশ্রয়ী শেয়ার্ড রুম। প্রতিজনের আলাদা সংরক্ষণ জায়গা আছে।",
    area: "Mohammadpur",
    address: "Tajmahal Road, Mohammadpur, Dhaka",
    lat: 23.7631,
    lng: 90.3589,
    rent_bdt: 4500,
    rooms: 1,
    bathrooms: 1,
    floor: 2,
    furnishing: "semi",
    type: "student",
    for_gender: "male",
    utilities_included: true,
    photos: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
    ],
    is_available: true,
    trust_score: 55,
    trust_score_breakdown: {
      price: { score: 25, note: "Rent is within expected range." },
      photos: { score: 20, note: "Excellent photo evidence." },
      description: { score: 15, note: "Clear description provided." },
      duplicate: { score: 10, note: "Passed NLP duplicate check." },
      photo_hash: { score: 15, note: "Original photos verified by pHash." }
    },
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    landlord_id: "landlord-7",
    title_en: "Luxury 3-Bed Flat – Gulshan-2",
    title_bn: "গুলশান-২ তে বিলাসবহুল ৩ রুমের ফ্ল্যাট",
    description_en: "Premium 3-bedroom apartment in prestigious Gulshan-2. Equipped with central AC, modern kitchen appliances, covered parking, and 24/7 guard service.",
    description_bn: "গুলশান-২ এর প্রিমিয়াম ৩ রুমের অ্যাপার্টমেন্ট। সেন্ট্রাল এসি, আধুনিক রান্নাঘর এবং পার্কিং সহ।",
    area: "Gulshan-2",
    address: "Road 48, House 12, Gulshan-2, Dhaka",
    lat: 23.7945,
    lng: 90.4145,
    rent_bdt: 45000,
    rooms: 3,
    bathrooms: 3,
    floor: 8,
    furnishing: "fully",
    type: "family",
    for_gender: "any",
    utilities_included: true,
    photos: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
    ],
    is_available: true,
    trust_score: 95,
    trust_score_breakdown: {
      price: { score: 25, note: "Rent is within expected range." },
      photos: { score: 20, note: "Excellent photo evidence." },
      description: { score: 15, note: "Clear description provided." },
      duplicate: { score: 10, note: "Passed NLP duplicate check." },
      photo_hash: { score: 15, note: "Original photos verified by pHash." }
    },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    landlord_id: "landlord-8",
    title_en: "2-Bed Sublet Available – Banani",
    title_bn: "বনানীতে ২ রুমের সাবলেট পাওয়া যাচ্ছে",
    description_en: "Well-maintained 2-bedroom sublet in Banani. Ideal for young professionals working in the corporate district. Walking distance to Banani commercial area.",
    description_bn: "বনানীতে সুসজ্জিত ২ রুমের সাবলেট। কর্পোরেট এলাকায় কর্মরত তরুণ পেশাদারদের জন্য আদর্শ।",
    area: "Banani",
    address: "Road 11, House 5, Banani, Dhaka",
    lat: 23.7937,
    lng: 90.4016,
    rent_bdt: 18000,
    rooms: 2,
    bathrooms: 2,
    floor: 6,
    furnishing: "fully",
    type: "professional",
    for_gender: "any",
    utilities_included: false,
    photos: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
    ],
    is_available: true,
    trust_score: 73,
    trust_score_breakdown: {
      price: { score: 25, note: "Rent is within expected range." },
      photos: { score: 20, note: "Excellent photo evidence." },
      description: { score: 15, note: "Clear description provided." },
      duplicate: { score: 10, note: "Passed NLP duplicate check." },
      photo_hash: { score: 15, note: "Original photos verified by pHash." }
    },
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
