import type { FlatmateProfile } from "@/types";

/** 8 realistic seed flatmate profiles for demo purposes */
export const SEED_PROFILES: FlatmateProfile[] = [
  {
    id: "p1",
    name: "Rahim Hossain",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rahim",
    university: "iut",
    university_priority: "commutable_both",
    budget_min: 6000,
    budget_max: 9000,
    preferred_areas: ["Gazipur", "Mirpur-1", "Mirpur-2"],
    looking_for_count: 1,
    move_in: "this_month",
    gender_pref: "male",
    sleep_schedule: "night_owl",
    wake_up: "after_9",
    study_style: "light_bg_ok",
    work_from_home: "sometimes",
    smoking: "non_smoker",
    cooking: "cook_share",
    kitchen_cleanliness: "reasonable",
    guests: "weekends_ok",
    cleanliness: "reasonable",
    noise_level: "music_tv_ok",
    social_style: "balanced",
    has_pet: false,
    pet_ok: true,
    self_description: "Chill & ambitious",
    ideal_flatmate: "Someone who respects quiet study hours but is fun on weekends.",
  },
  {
    id: "p2",
    name: "Farhan Ahmed",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Farhan",
    university: "diu",
    university_priority: "commutable_both",
    budget_min: 5000,
    budget_max: 8000,
    preferred_areas: ["Mirpur-1", "Mirpur-2", "Pallabi"],
    looking_for_count: 1,
    move_in: "this_month",
    gender_pref: "any",
    sleep_schedule: "night_owl",
    wake_up: "after_9",
    study_style: "headphones",
    work_from_home: "no",
    smoking: "non_smoker",
    cooking: "flexible",
    kitchen_cleanliness: "reasonable",
    guests: "weekends_ok",
    cleanliness: "reasonable",
    noise_level: "music_tv_ok",
    social_style: "extrovert",
    has_pet: false,
    pet_ok: true,
    self_description: "Friendly & creative",
    ideal_flatmate: "A non-smoker who doesn't mind occasional guests and splits chores fairly.",
  },
  {
    id: "p3",
    name: "Tanvir Islam",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvir",
    university: "buet",
    university_priority: "near_my_uni",
    budget_min: 7000,
    budget_max: 12000,
    preferred_areas: ["Azimpur", "Lalbagh", "Dhanmondi"],
    looking_for_count: 1,
    move_in: "within_week",
    gender_pref: "male",
    sleep_schedule: "early_bird",
    wake_up: "before_7",
    study_style: "deep_silence",
    work_from_home: "sometimes",
    smoking: "non_smoker",
    cooking: "cook_alone",
    kitchen_cleanliness: "spotless",
    guests: "rarely",
    cleanliness: "spotless",
    noise_level: "quiet",
    social_style: "introvert",
    has_pet: false,
    pet_ok: false,
    self_description: "Focused & disciplined",
    ideal_flatmate: "A quiet, studious person who keeps the flat clean and respects personal space.",
  },
  {
    id: "p4",
    name: "Sabbir Rahman",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sabbir",
    university: "du",
    university_priority: "near_my_uni",
    budget_min: 5000,
    budget_max: 8000,
    preferred_areas: ["Azimpur", "Lalbagh", "Shahbag"],
    looking_for_count: 2,
    move_in: "next_month",
    gender_pref: "male",
    sleep_schedule: "flexible",
    wake_up: "7_to_9",
    study_style: "light_bg_ok",
    work_from_home: "no",
    smoking: "non_smoker",
    cooking: "cook_share",
    kitchen_cleanliness: "reasonable",
    guests: "weekends_ok",
    cleanliness: "reasonable",
    noise_level: "music_tv_ok",
    social_style: "balanced",
    has_pet: false,
    pet_ok: true,
    self_description: "Easy-going & social",
    ideal_flatmate: "Someone friendly who enjoys cooking together and shares costs fairly.",
  },
  {
    id: "p5",
    name: "Nusrat Jahan",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nusrat",
    university: "nsu",
    university_priority: "near_my_uni",
    budget_min: 8000,
    budget_max: 14000,
    preferred_areas: ["Bashundhara R/A", "Baridhara", "Badda"],
    looking_for_count: 1,
    move_in: "this_month",
    gender_pref: "female",
    sleep_schedule: "early_bird",
    wake_up: "before_7",
    study_style: "deep_silence",
    work_from_home: "yes_daily",
    smoking: "non_smoker",
    cooking: "cook_alone",
    kitchen_cleanliness: "spotless",
    guests: "rarely",
    cleanliness: "spotless",
    noise_level: "quiet",
    social_style: "introvert",
    has_pet: false,
    pet_ok: false,
    self_description: "Ambitious & tidy",
    ideal_flatmate: "A female student who is serious about studies, keeps the flat spotless, and respects privacy.",
  },
  {
    id: "p6",
    name: "Sadia Islam",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sadia",
    university: "brac",
    university_priority: "commutable_both",
    budget_min: 7000,
    budget_max: 12000,
    preferred_areas: ["Mohakhali", "Banani", "Gulshan-1"],
    looking_for_count: 1,
    move_in: "this_month",
    gender_pref: "female",
    sleep_schedule: "flexible",
    wake_up: "7_to_9",
    study_style: "light_bg_ok",
    work_from_home: "sometimes",
    smoking: "non_smoker",
    cooking: "flexible",
    kitchen_cleanliness: "reasonable",
    guests: "weekends_ok",
    cleanliness: "reasonable",
    noise_level: "music_tv_ok",
    social_style: "balanced",
    has_pet: false,
    pet_ok: true,
    self_description: "Cheerful & responsible",
    ideal_flatmate: "A female flatmate who is tidy, social but not too loud, and good at splitting expenses.",
  },
  {
    id: "p7",
    name: "Mehedi Hasan",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mehedi",
    university: "aiub",
    university_priority: "commutable_both",
    budget_min: 5000,
    budget_max: 9000,
    preferred_areas: ["Mirpur-11", "Mirpur-12", "Pallabi"],
    looking_for_count: 2,
    move_in: "flexible",
    gender_pref: "male",
    sleep_schedule: "night_owl",
    wake_up: "after_9",
    study_style: "headphones",
    work_from_home: "no",
    smoking: "smoker_outside",
    cooking: "dont_cook",
    kitchen_cleanliness: "relaxed",
    guests: "often",
    cleanliness: "relaxed",
    noise_level: "dont_care",
    social_style: "extrovert",
    has_pet: false,
    pet_ok: true,
    self_description: "Fun & spontaneous",
    ideal_flatmate: "Someone chill who doesn't stress about a bit of mess and enjoys hanging out.",
  },
  {
    id: "p8",
    name: "Rakib Hossain",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rakib",
    university: "duet",
    university_priority: "near_my_uni",
    budget_min: 4000,
    budget_max: 7000,
    preferred_areas: ["Gazipur", "Tongi", "Boardbazar"],
    looking_for_count: 1,
    move_in: "this_month",
    gender_pref: "male",
    sleep_schedule: "early_bird",
    wake_up: "before_7",
    study_style: "light_bg_ok",
    work_from_home: "no",
    smoking: "non_smoker",
    cooking: "cook_share",
    kitchen_cleanliness: "reasonable",
    guests: "rarely",
    cleanliness: "reasonable",
    noise_level: "quiet",
    social_style: "introvert",
    has_pet: false,
    pet_ok: false,
    self_description: "Hardworking & calm",
    ideal_flatmate: "A non-smoker who is punctual, budget-conscious, and keeps things orderly.",
  },
];

/** Pre-computed area suggestions for cross-university pairs */
export const UNI_AREA_OVERLAP: Record<string, string[]> = {
  "iut-duet":  ["Gazipur", "Boardbazar", "Tongi"],
  "iut-diu":   ["Mirpur-1", "Mirpur-2", "Pallabi"],
  "iut-aiub":  ["Mirpur-11", "Mirpur-12", "Uttara"],
  "duet-diu":  ["Mirpur-1", "Pallabi", "Mirpur-2"],
  "buet-du":   ["Azimpur", "Lalbagh", "Shahbag"],
  "buet-brac": ["Dhanmondi", "Mohammadpur", "Shyamoli"],
  "nsu-brac":  ["Mohakhali", "Banani", "Gulshan-1"],
  "nsu-aiub":  ["Bashundhara R/A", "Baridhara", "Badda"],
  "du-brac":   ["Shahbag", "Mohakhali", "Tejgaon"],
  "diu-aiub":  ["Ashulia", "Savar", "Mirpur-1"],
};

export function getSharedAreas(uniA: string, uniB: string): string[] {
  const key1 = `${uniA}-${uniB}`;
  const key2 = `${uniB}-${uniA}`;
  return UNI_AREA_OVERLAP[key1] || UNI_AREA_OVERLAP[key2] || [];
}
